### ISSUE TITLE
APIError(code=-1022): Signature for this request is not valid

### ISSUE THREAD

**Issue by pancho111203** [sammchardy/python-binance#68] opened 2017-12-31 10:08 UTC
Getting this error when I try to create any order. I'm using version 0.5.12.

Examples that cause this error:

order = client.create_order(
            symbol='BNBETH', side=SIDE_SELL, type=ORDER_TYPE_MARKET,
            quantity=0.1)

order = client.order_market_sell(
    symbol='BTCETH',
    quantity=1)

and more...

**Comment by sammchardy** [comment] 2018-01-01 10:07
Duplicate of issue #5 

Possibly fixed in new release v0.5.13

**Closed by sammchardy** 2018-01-01 10:07 UTC

**Comment by akaniklaus** [comment] 2018-03-19 13:56
@sammchardy Would this be resolved in the version that I just installed using pip, or do I have to do anything else to install v0.5.13. I wasn't receiving this error but since that I moved my code to another server which is at Tokyo (that meant to be closer to Binance servers and have less latency). I started to receiving this error very often. Can you please suggest what should I make?

**Comment by tamycova** [comment] 2018-03-25 00:17
@akaniklaus the API is already in version 0.6.7, it shouldn't really matter the location of the code so maybe check the version you have in the Tokyo server

**Comment by akaniklaus** [comment] 2018-03-25 17:21
@tamycova Yes I already updated to that version (installed via setup.py after fetching the repository rather than using pip), the problem persists. Greetings to Chile, I was living in Santiago previous year.

**Comment by HugoPeters1024** [comment] 2019-02-07 10:34
Did you ever solve this problem? I'm using a different library but I have this same issue ALWAYS on the CI server and NEVER on my local machine. I've already tried generating new keys and messing with the receiveWindow but no luck.

**Comment by thirstygerry** [comment] 2020-04-24 11:21
If someone still needs it, I created an example python script that returns your balances.
It includes a valid signature.
https://github.com/thirstygerry/binance-python

**Comment by gtellezgiron** [comment] 2022-05-20 11:33
I am having a similar problem. Did you ever solved it?

**Comment by thirstygerry** [comment] 2022-05-23 07:23
I did, please see my comment of Apr 24, 2020
