### ISSUE TITLE
How to buy or sell 'max amount'

### ISSUE THREAD

**Issue by msieg** [sammchardy/python-binance#113] opened 2018-01-14 17:46 UTC
Hi, can someone please tell me how to buy or sell the maximum possible amount (the 100% option) through the market or limit api call? I don't want to check my balance and determine the number of coins I can buy or sell, I just want to say 'max amount' like you can do in the GUI. Thanks.

**Comment by sammchardy** [comment] 2018-01-15 06:10
Hi @msieg this is a duplicate of the discussion on issue #89

**Closed by sammchardy** 2018-01-15 06:10 UTC
