### ISSUE TITLE
Freezes when trying to close the socket

### ISSUE THREAD

**Issue by Ramesses3** [sammchardy/python-binance#1503] opened 2024-12-06 06:53 UTC
**Describe the bug**
I use a fairly loaded multiplex websocket, which contains data on 300+ tickers. When updating the ticker list, I need to restart the socket with new subscriptions. Very often, when restarting, the socket simply freezes when the connection is closed.

**To Reproduce**
A very simplified code example that simply receives one message from a stream and restarts the socket.
```python
import asyncio
from binance import AsyncClient, BinanceSocketManager
import logging

logging.basicConfig(level=logging.DEBUG, filename="debug.log",filemode="a", format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger()

async def test(client, bsm):
  INTERVAL = '1m'
  SUBSCRIPTIONS = []
  tickers_list = await client.get_ticker()
  for ticker in tickers_list[:350]:
    symbol = ticker.get('symbol').lower()
    SUBSCRIPTIONS.append(f'{symbol}@kline_{INTERVAL}')
  while True:
    logger.info('Opening websocket...')
    ws = bsm.multiplex_socket(SUBSCRIPTIONS)
    async with ws as stream:
      while True:
      msg = await stream.recv()
        logger.info(msg)
        break

async def run():
  client = await AsyncClient.create(testnet=False)
  bsm = BinanceSocketManager(client)
 await asyncio.gather(test(client, bsm))

asyncio.run(run())
```
**Expected behavior**
Continuous operation

**Environment**
 - Python version: **3.9.19**
 - Virtual Env: **no**
 - OS: **AlmaLinux 9 5.14.0-503.14.1.el9_5.x86_64** 
 - python-binance **1.0.24**

**Logs**
See the attached file. This time, the hang occurred on the first attempt to restart the socket.
[debug.log](https://github.com/user-attachments/files/18033802/debug.log)

**Additional context**
The hang may occur immediately or after a short period of operation. Adding pauses between closing and opening the socket does not solve the problem.

**Comment by pcriadoperez** [comment] 2024-12-07 14:44
Hi @Ramesses3, Thanks for notifying, I'll look into this

**Comment by pcriadoperez** [comment] 2024-12-08 15:26
Hi @Ramesses3 , I was not able to reproduce the error. Can you see if it still happens on the latest version?
Are you able to reproduce consistently with the code you provided?

**Comment by Ramesses3** [comment] 2024-12-09 20:44
Hello @pcriadoperez,
Today I tried to reproduce the error using python-binance version **1.0.25**. The problem did not show up. I will look further.

**But that's not the worst part**
While testing freezes, I noticed something similar to a memory leak in my code (the code is exactly from my first message). In the next terminal window, I launched "top" and noticed that the amount of memory used by the program is constantly growing.

![2024-12-09_23-05](https://github.com/user-attachments/assets/6bbe738e-7009-4961-b4b5-e8205aea4dd6)
This really upset me, because now there is a project in the works that will use about a hundred websockets at the same time. I tested it for leaks and there are leaks too. I didn't pay attention to this before, because I didn't run the code for a long time.

Please pay attention to this problem. If necessary, I will move it to a new topic.

**Comment by pcriadoperez** [comment] 2024-12-11 04:34
@Ramesses3, Glad to hear about the socket close issue being solved.

For the memory leak I changed the initial code you sent to record the memory on every loop. I do see a slight increase over time, but each time the garbage collection runs it does seem to go back to the initial value.
How much of an increase in memory usage are you seeing?

**Comment by Ramesses3** [comment] 2024-12-11 11:57
Hello @pcriadoperez , first of all, I want to thank you for your prompt response and participation.

As for the problem of memory leaks, perhaps you were right and I jumped to conclusions. I think it is necessary to observe the work of the code under load for several days.
I will do this and let you know the result.

**Comment by pcriadoperez** [comment] 2024-12-12 05:02
sounds good! I appreciate the reports!
I'll close this issue for now, but feel free to open another one if you find anything

**Closed by pcriadoperez** 2024-12-12 05:02 UTC
